on:
  push:
   branches:
     - master
pull_request:
branches:
- dev

jobs:
deploy:
runs-on: Ubuntu-latest
build:
  name: Build
  runs-on: Ubuntu-latest

steps:
- name: Checkout code
uses: actions/checkout@v2

- name: Use Node.js
uses: actions/setup-node@v1
with:
node-version: 13.x

- name: Install NPM packages
- run: npm install
- run: npm run build --if-present

- name: Deploy to Netlify
  run: npm run build
uses: netlify/actions/cli@master
env:
NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
NETLIFY_SITE_ID: ${{ secrets.DEV_NETLIFY_SITE_ID }}
with:
args: deploy --dir=build --prod
secrets: '["DEV_NETLIFY_AUTH_TOKEN", "NETLIFY_SITE_ID"]'
- name: Run tests
  run: npm run test

- name: Uplode production-ready build files
  uses: actions/uplode-artifact@v2
with:
  name: production-files
  path: ./build
deploy:
  name: Deploy
  needs: build
  runs-on: Ubuntu-latest
if: github.ref == 'refs/heads/master'

steps:
  - name: Download artifact
  uses: actions/download-artifact@v2
  with:
    name: production-files
    path: ./build

- name: Deploy to gh-pages
uses: peaceiris/actions-gh-pages@v3

- name: Deploy to Netlify
uses: 
with:
  github_token: ${{ secrets.GITHUB_TOKEN }}
  publish_dir: ./build

actions:
- action: "Deploy"
  type: "NETLIFY"
  application_name: "COUNTER-APP"
  site_id: "2a3ee62a-3300-4039-a6f9-a7b8cd2fb564"
  setup_commands:
  - "apt-get update && apt-get -y install git"
  execute_commands:
  - "netlify deploy --dir=$netlify_dir"
  integration_hash: "5ddb7c180fb38be67bd78a88a"
  shell: "SH"
  variables:
  - key: "netlify_dir",
  value: "directory_name"