actions:
- action: "Deploy to application-42707"
  type: "NETLIFY"
  application_name: "application-42707"
  site_id: "2a3ee62a-3300-4039-a6f9-a7b8cd2fb564"
  setup_commands:
  - "apt-get update && apt-get -y install git"
  execute_commands:
  - "netlify deploy --dir=$netlify_dir"
  integration_hash: "5ddb7c180fb38be67bd78a88a"
  shell: "SH"
  variables:
  - key: "netlify_dir",
  value: "directory_name"